/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxIPC */

#ifndef _Included_LinuxIPC
#define _Included_LinuxIPC
#ifdef __cplusplus
extern "C" {
#endif
#undef LinuxIPC_IPC_CREAT
#define LinuxIPC_IPC_CREAT 512L
#undef LinuxIPC_IPC_EXCL
#define LinuxIPC_IPC_EXCL 1024L
#undef LinuxIPC_IPC_NOWAIT
#define LinuxIPC_IPC_NOWAIT 2048L
#undef LinuxIPC_MSG_NOERROR
#define LinuxIPC_MSG_NOERROR 4096L
#undef LinuxIPC_MSG_EXCEPT
#define LinuxIPC_MSG_EXCEPT 8192L
#undef LinuxIPC_IPC_RMID
#define LinuxIPC_IPC_RMID 0L
#undef LinuxIPC_IPC_SET
#define LinuxIPC_IPC_SET 1L
#undef LinuxIPC_IPC_STAT
#define LinuxIPC_IPC_STAT 2L
#undef LinuxIPC_SHM_RDONLY
#define LinuxIPC_SHM_RDONLY 4096L
#undef LinuxIPC_SHM_RND
#define LinuxIPC_SHM_RND 8192L
#undef LinuxIPC_EAGAIN
#define LinuxIPC_EAGAIN 11L
/*
 * Class:     LinuxIPC
 * Method:    mkfifo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_mkfifo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LinuxIPC
 * Method:    ftok
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_ftok
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     LinuxIPC
 * Method:    msgget
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_msgget
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    msgsnd
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_msgsnd
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    msgrcv
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_msgrcv
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    msgRmid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_msgRmid
  (JNIEnv *, jobject, jint);

/*
 * Class:     LinuxIPC
 * Method:    semget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semget
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    semop
 * Signature: (I[LLinuxIPC/Sembuf;I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semop
  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     LinuxIPC
 * Method:    semtimedop
 * Signature: (I[LLinuxIPC/Sembuf;IJJ)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semtimedop
  (JNIEnv *, jobject, jint, jobjectArray, jint, jlong, jlong);

/*
 * Class:     LinuxIPC
 * Method:    semRmid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semRmid
  (JNIEnv *, jobject, jint);

/*
 * Class:     LinuxIPC
 * Method:    semGetVal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semGetVal
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    semSetVal
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semSetVal
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    semGetNCnt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_semGetNCnt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_shmget
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmat
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_shmat
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmdt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_shmdt
  (JNIEnv *, jobject, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmWrite
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_LinuxIPC_shmWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmRead
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_LinuxIPC_shmRead
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     LinuxIPC
 * Method:    shmRmid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_LinuxIPC_shmRmid
  (JNIEnv *, jobject, jint);

/*
 * Class:     LinuxIPC
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LinuxIPC_strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
