/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxIPC_Msqid_ds */

#ifndef _Included_LinuxIPC_Msqid_ds
#define _Included_LinuxIPC_Msqid_ds
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
