/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxIPC_Sembuf */

#ifndef _Included_LinuxIPC_Sembuf
#define _Included_LinuxIPC_Sembuf
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
