/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxIPC_Ipc_perm */

#ifndef _Included_LinuxIPC_Ipc_perm
#define _Included_LinuxIPC_Ipc_perm
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
