/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SharedMemoryStreams */

#ifndef _Included_SharedMemoryStreams
#define _Included_SharedMemoryStreams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SharedMemoryStreams
 * Method:    initStream
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_SharedMemoryStreams_initStream
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     SharedMemoryStreams
 * Method:    sendData
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_SharedMemoryStreams_sendData
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     SharedMemoryStreams
 * Method:    fillBuffer
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_SharedMemoryStreams_fillBuffer
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     SharedMemoryStreams
 * Method:    close
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_SharedMemoryStreams_close
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     SharedMemoryStreams
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SharedMemoryStreams_strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
