/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowsipc_Mailslot */

#ifndef _Included_windowsipc_Mailslot
#define _Included_windowsipc_Mailslot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowsipc_Mailslot
 * Method:    create
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_windowsipc_Mailslot_create
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     windowsipc_Mailslot
 * Method:    write
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_windowsipc_Mailslot_write
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     windowsipc_Mailslot
 * Method:    read
 * Signature: (Ljava/lang/String;JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_windowsipc_Mailslot_read
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     windowsipc_Mailslot
 * Method:    remove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_windowsipc_Mailslot_remove
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
