/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowsipc_BaseIpc */

#ifndef _Included_windowsipc_BaseIpc
#define _Included_windowsipc_BaseIpc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowsipc_BaseIpc
 * Method:    ping
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_windowsipc_BaseIpc_ping
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
