/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windowsipc_PingJni */

#ifndef _Included_windowsipc_PingJni
#define _Included_windowsipc_PingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windowsipc_PingJni
 * Method:    ping
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_windowsipc_PingJni_ping
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
