/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowsIPC */

#ifndef _Included_WindowsIPC
#define _Included_WindowsIPC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowsIPC
 * Method:    createMailslot
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_WindowsIPC_createMailslot
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WindowsIPC
 * Method:    createPipe
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_WindowsIPC_createPipe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WindowsIPC
 * Method:    createNamedPipe
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_WindowsIPC_createNamedPipe
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
